"""ONNX file and archive inspection APIs."""

from .inspector import (
    InspectionError,
    InspectionLimits,
    MemoryConfirmationRequired,
    inspect_7z,
    inspect_archive,
    inspect_onnx,
    inspect_path,
    inspect_rar,
    inspect_tar,
    source_format,
    supported_input_suffixes,
)
from .report import (
    AttributeReport,
    GraphReport,
    InspectionReport,
    ModelError,
    ModelReport,
    OperatorCount,
    OperatorReport,
    OperatorSemanticsReport,
    OpsetReport,
    TensorValueReport,
)

__all__ = [
    "AttributeReport",
    "GraphReport",
    "InspectionError",
    "InspectionLimits",
    "InspectionReport",
    "MemoryConfirmationRequired",
    "ModelError",
    "ModelReport",
    "OperatorCount",
    "OperatorReport",
    "OperatorSemanticsReport",
    "OpsetReport",
    "TensorValueReport",
    "inspect_7z",
    "inspect_archive",
    "inspect_onnx",
    "inspect_path",
    "inspect_rar",
    "inspect_tar",
    "source_format",
    "supported_input_suffixes",
]
